#cloud-config
hostname: {hostname}
package_update: true
package_upgrade: true

timezone: UTC

users:
  - name: {username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - {sshPubKey}

runcmd:
  # Install dependencies
  - sudo apt-get update
  - sudo apt-get install -y libicu74 jq curl wget git apt-transport-https ca-certificates gnupg lsb-release libssl3 libssl-dev openssl
  # Install docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo usermod -aG docker {username}
  - sudo systemctl enable docker
  - sudo systemctl start docker
  - sudo systemctl enable containerd.service